M48
; DRILL file {KiCad (6.0.2)} date Mon Apr 18 11:06:25 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-18T11:06:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X4.5362Y-3.2373
X4.8695Y-1.5962
X5.8695Y-3.2373
X6.8695Y-1.5962
X7.2027Y-3.2373
T0
M30
